### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by oussbenj** [dbrgn/crazyflie2-hcsr04#3]
I want to use [Sourcegraph](https://sourcegraph.com) for crazyflie2-hcsr04 code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/dbrgn/crazyflie2-hcsr04. (It should only take 30 seconds.)

Thank you!

**Comment by dbrgn** [comment]
Done. Although I doubt it helps you much. There is no code in this repository.

**Comment by oussbenj** [comment]
i wanna ask about the firmware of the CF that you used with the HC SR-04
thank you

**Comment by dbrgn** [comment]
It's not done yet :) I started some time ago but didn't finish yet.
